language: bash
sudo: required

install:
  - wget https://releases.hashicorp.com/terraform/0.11.5/terraform_0.11.5_linux_amd64.zip
  - unzip terraform_0.11.5_linux_amd64.zip
  - mv terraform /usr/local/bin

script:
  - terraform init
  - terraform plan

#after_success:
#- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then terraform apply; fi

