language: bash
sudo: required

install:
  - wget https://releases.hashicorp.com/terraform/0.11.5/terraform_0.11.5_linux_amd64.zip
  - unzip terraform_0.11.5_linux_amd64.zip
  - sudo mv terraform /usr/local/bin
  - sudo apt-get update && sudo apt-get install jq

post_install:
  - sed -i "s/\${file(\"\/home\/user\/.ssh\/id_rsa\")\}/\$\{var.private_key}/g" master.tf
  - sed -i "s/\${file(\"\/home\/user\/.ssh\/id_rsa\")\}/\$\{var.private_key}/g" node.tf

script:
  - terraform init
  - terraform plan

#after_success:
#- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then terraform apply; fi

